import type { SkillDefinition } from "@/core/skills/types";

export const builtInSkills: SkillDefinition[] = [
  {
    id: "frontend",
    name: "Frontend Implementation",
    scope: "global",
    description: "Build and refine UI flows with robust accessibility and responsive behavior.",
    instructions: [
      "Map user goals to component-level task decomposition.",
      "Preserve design system constraints and accessibility semantics.",
    ],
    toolRules: ["Prefer repo component primitives", "Capture screenshots for visual diffs"],
    acceptanceCriteria: ["No accessibility regressions", "Visual verification artifacts attached"],
    preferredModelAliases: ["ux-premium", "balanced-coder"],
    outputFormat: "component_diff + ui_walkthrough",
  },
  {
    id: "backend",
    name: "Backend/API",
    scope: "global",
    description: "Implement backend logic, schemas, and API routes with testing.",
    instructions: ["Design contracts first", "Add targeted validation and failure paths"],
    toolRules: ["Run targeted tests", "Attach migration/log evidence when data changes"],
    acceptanceCriteria: ["Contract coverage present", "Test output artifact attached"],
    preferredModelAliases: ["reasoning-strong", "balanced-coder"],
    outputFormat: "api_diff + verification_notes",
  },
  {
    id: "design",
    name: "Design System",
    scope: "global",
    description: "Guide hierarchy, spacing, typography, and interaction consistency.",
    instructions: ["Prefer restrained visual language", "Optimize readability and focus"],
    toolRules: ["No decorative noise", "Use meaningful motion only"],
    acceptanceCriteria: ["Hierarchy improvements are explicit", "Before/after evidence attached"],
    preferredModelAliases: ["ux-premium"],
    outputFormat: "design_notes + screenshots",
  },
  {
    id: "animation",
    name: "Motion & Animation",
    scope: "global",
    description: "Add subtle, purposeful motion that clarifies state transitions.",
    instructions: ["Animate intent, not decoration", "Ensure reduced-motion support"],
    toolRules: ["Keep durations short and deliberate"],
    acceptanceCriteria: ["Motion supports comprehension", "No performance regressions"],
    preferredModelAliases: ["ux-premium"],
    outputFormat: "motion_spec + preview_capture",
  },
  {
    id: "testing",
    name: "Testing & Verification",
    scope: "global",
    description: "Create targeted tests and runtime verification artifacts.",
    instructions: ["Test changed behavior directly", "Summarize evidence and residual risk"],
    toolRules: ["Do not remove unrelated tests"],
    acceptanceCriteria: ["Failing scenario covered", "Verification artifact attached"],
    preferredModelAliases: ["reasoning-strong"],
    outputFormat: "test_plan + test_output",
  },
  {
    id: "docs",
    name: "Documentation",
    scope: "global",
    description: "Update technical documentation and walkthroughs tied to implementation.",
    instructions: ["Document decisions and tradeoffs", "Keep docs aligned with shipped behavior"],
    toolRules: ["Avoid speculative docs"],
    acceptanceCriteria: ["Docs linked to changed modules"],
    preferredModelAliases: ["balanced-coder"],
    outputFormat: "doc_diff + walkthrough",
  },
  {
    id: "devops",
    name: "DevOps & Delivery",
    scope: "global",
    description: "Handle CI, deployment, environment, and operational hardening concerns.",
    instructions: ["Prioritize reproducibility", "Expose observability hooks"],
    toolRules: ["Capture command logs", "Use approvals for destructive ops"],
    acceptanceCriteria: ["Operational rollback path exists"],
    preferredModelAliases: ["reasoning-strong"],
    outputFormat: "ops_plan + logs",
  },
];
